# Standalone Three.jl port for:
#   https://threejs.org/examples/#webgl_instancing_dynamic

import Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Three

const OUT = joinpath(@__DIR__, "output")
isdir(OUT) || mkpath(OUT)

function build_instances()
    n = 11
    count = n * n
    mat = MeshStandardMaterial(color=Color3(0.32, 0.78, 1.0),
                               metalness=0.18, roughness=0.34)
    inst = InstancedMesh(BoxGeometry(width=0.34, height=0.34, depth=0.34),
                         mat, count; name="instancing_dynamic_grid",
                         cast_shadow=true, receive_shadow=true)
    k = 0
    for ix in 1:n, iz in 1:n
        x = (ix - (n + 1) / 2) * 0.55
        z = (iz - (n + 1) / 2) * 0.55
        r = hypot(x, z)
        y = 0.3 + 0.35 * sin(2.3r)
        s = 0.75 + 0.35 * cos(1.7r)
        rot = mat4_rotation_y(0.7x) * mat4_rotation_x(0.55z)
        k += 1
        set_instance_matrix!(inst, k,
                             mat4_translation(x, y, z) *
                             rot *
                             mat4_scaling(s, s, s))
    end
    return inst
end

function build_case()
    scene = Scene(background=Color3(0.010, 0.012, 0.018),
                  fog=FogExp2(color=Color3(0.010, 0.012, 0.018), density=0.045))
    add!(scene, AmbientLight(color=Color3(0.45, 0.52, 0.62), intensity=0.75))
    key = DirectionalLight(color=Color3(1.0, 0.94, 0.82), intensity=1.25,
                           position=Vec3(4.0, 6.0, 5.0), cast_shadow=true)
    key.target = Vec3(0.0, 0.0, 0.0)
    add!(scene, key)
    add!(scene, PointLight(color=Color3(0.35, 0.62, 1.0), intensity=16.0,
                           distance=9.0, decay=2.0, position=Vec3(-3.0, 3.0, 2.5)))

    floor = Mesh(PlaneGeometry(width=8.5, height=8.5),
                 MeshStandardMaterial(color=Color3(0.18, 0.20, 0.24), roughness=0.85);
                 name="instancing_dynamic_floor", receive_shadow=true)
    floor.rotation = Euler(-pi / 2, 0.0, 0.0)
    add!(scene, floor)

    inst = build_instances()
    add!(scene, inst)

    clip = AnimationClip("instancing_spin", AbstractKeyframeTrack[
        QuaternionKeyframeTrack(inst, :rotation, [0.0, 3.0, 6.0],
                                [Quaternion(),
                                 quat_from_euler(0.0, pi, 0.0),
                                 quat_from_euler(0.0, 2pi, 0.0)]),
        KeyframeTrack(inst, :scale, [0.0, 1.5, 3.0],
                      [Vec3(1.0, 1.0, 1.0), Vec3(1.08, 1.08, 1.08),
                       Vec3(1.0, 1.0, 1.0)])
    ]; loop=:repeat)

    WebGLExportCase("instancing-dynamic", "Instancing Dynamic",
                    "Animated InstancedMesh grid generated by Three.jl.",
                    scene; target=Vec3(0.0, 0.7, 0.0), radius=7.5, height=4.2,
                    fov=pi / 4.2, animations=[clip],
                    tone_mapping=:aces, tone_exposure=1.15,
                    output_color_space=:srgb)
end

function main()
    html = save_webgl_html(joinpath(OUT, "webgl_instancing_dynamic.html"), [build_case()])
    println("WEBGL_INSTANCING_DYNAMIC_OK $html")
end

main()
