# Standalone Diff3D.jl partial port for:
#   https://threejs.org/examples/#webgl_geometry_shapes

import Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Diff3D

const OUT = joinpath(@__DIR__, "output")
isdir(OUT) || mkpath(OUT)

function uv_grid_texture(; n::Int=64)
    data = ones(Float64, n, n, 4)
    for y in 1:n, x in 1:n
        grid = (x - 1) % 8 == 0 || (y - 1) % 8 == 0
        check = (fld(x - 1, 8) + fld(y - 1, 8)) % 2 == 0
        data[y, x, 1] = grid ? 0.05 : (check ? 0.96 : 0.18)
        data[y, x, 2] = grid ? 0.05 : (check ? 0.78 : 0.32)
        data[y, x, 3] = grid ? 0.05 : (check ? 0.28 : 0.86)
        data[y, x, 4] = 1.0
    end
    Texture(data; repeat=Vec2(3.0, 3.0), filter=:nearest, colorspace=:srgb)
end

function regular_shape(n::Int; radius::Float64=1.0, phase::Float64=0.0)
    n >= 3 || throw(ArgumentError("regular_shape needs at least three vertices"))
    [Vec2(radius * cos(phase + 2pi * i / n), radius * sin(phase + 2pi * i / n))
     for i in 0:(n - 1)]
end

function rectangle_shape(width::Float64, height::Float64)
    hw = width / 2
    hh = height / 2
    [Vec2(-hw, -hh), Vec2(hw, -hh), Vec2(hw, hh), Vec2(-hw, hh)]
end

function line_loop_geometry(shape::Vector{<:Vec2})
    positions = Float64[]
    for pt in shape
        append!(positions, (pt.x, pt.y, 0.0))
    end
    BufferGeometry(positions, Float64[], Float64[], Int[], length(shape), 0)
end

function add_shape_set!(group::Group, shape::Vector{<:Vec2}, name::String,
                        color::Color3, x::Float64; texture)
    textured = Mesh(ShapeGeometry(shape),
                    MeshPhongMaterial(color=Color3(1.0, 1.0, 1.0),
                                      map=texture, side=:double);
                    name="$(name)_textured_shape")
    textured.position = Vec3(x, 0.95, -0.9)
    textured.rotation = Euler(-0.18, 0.0, 0.0)
    add!(group, textured)

    flat = Mesh(ShapeGeometry(shape),
                MeshPhongMaterial(color=color, side=:double, shininess=22.0);
                name="$(name)_flat_shape")
    flat.position = Vec3(x, 0.95, 0.0)
    flat.rotation = Euler(-0.18, 0.0, 0.0)
    add!(group, flat)

    extruded = Mesh(ExtrudeGeometry(shape, depth=0.38),
                    MeshPhongMaterial(color=color, side=:double, shininess=38.0);
                    name="$(name)_extruded_shape")
    extruded.position = Vec3(x, -0.85, 0.0)
    extruded.rotation = Euler(-0.34, 0.22, 0.0)
    add!(group, extruded)

    outline = LineLoop(line_loop_geometry(shape),
                       LineBasicMaterial(color=color, linewidth=2.0);
                       name="$(name)_outline")
    outline.position = Vec3(x, -0.85, -0.62)
    outline.rotation = Euler(-0.34, 0.22, 0.0)
    add!(group, outline)
    return nothing
end

function build_case()
    scene = Scene(background=Color3(0.93, 0.94, 0.96),
                  fog=Fog(color=Color3(0.93, 0.94, 0.96), near=10.0, far=22.0))
    add!(scene, AmbientLight(color=Color3(0.45, 0.48, 0.52), intensity=0.65))
    add!(scene, DirectionalLight(color=Color3(1.0, 0.95, 0.88), intensity=1.5,
                                 position=Vec3(2.5, 4.0, 4.5)))
    add!(scene, PointLight(color=Color3(0.35, 0.55, 1.0), intensity=2.2,
                           distance=8.0, position=Vec3(-3.2, 1.6, 3.0)))
    add!(scene, GridHelper(8.0, 16; color=Color3(0.58, 0.62, 0.68)))

    group = Group(name="shape_geometry_group")
    add!(scene, group)
    texture = uv_grid_texture()
    add_shape_set!(group, regular_shape(3; radius=0.74, phase=pi / 2),
                   "triangle", Color3(0.94, 0.34, 0.18), -2.25; texture=texture)
    add_shape_set!(group, rectangle_shape(1.28, 0.92),
                   "rectangle", Color3(0.20, 0.63, 0.95), 0.0; texture=texture)
    add_shape_set!(group, regular_shape(6; radius=0.76, phase=pi / 6),
                   "hexagon", Color3(0.26, 0.74, 0.42), 2.25; texture=texture)

    clip = AnimationClip("shapes-spin", AbstractKeyframeTrack[
        QuaternionKeyframeTrack(group, :rotation, [0.0, 4.0, 8.0],
                                [Quaternion(),
                                 quat_from_euler(0.0, pi, 0.0),
                                 quat_from_euler(0.0, 2pi, 0.0)])
    ]; loop=:repeat)

    WebGLExportCase("geometry-shapes", "Geometry Shapes",
                    "Convex ShapeGeometry, ExtrudeGeometry, textured caps, and line outlines generated by Diff3D.jl.",
                    scene; target=Vec3(0.0, 0.0, 0.0), radius=8.2, height=2.2,
                    fov=pi / 4, animations=[clip],
                    tone_mapping=:reinhard, tone_exposure=1.05,
                    output_color_space=:srgb)
end

function main()
    html = save_webgl_html(joinpath(OUT, "webgl_geometry_shapes.html"), [build_case()])
    println("WEBGL_GEOMETRY_SHAPES_OK $html")
end

main()
