name: Release validation

"on":
  workflow_dispatch:

permissions:
  contents: read

jobs:
  consumer:
    uses: ./.github/workflows/consumer.yml
  platforms:
    uses: ./.github/workflows/ci.yml
    with:
      full_platform: true
